spring:
  main:
    web-application-type: servlet 
  
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbotdb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      separator: ;;
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080} # Render의 PORT 환경변수 바인딩 허용

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    disable-swagger-default-url: true

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: "https://api.openai.com"
  model: gpt-4o-mini
  timeout-ms: 30000

spring.data.redis:
  host: ${REDIS_HOST:localhost} # 배포 환경 고려
  port: ${REDIS_PORT:6379}

app:
  rate-limit:
    enabled: true
    limit: 10
    window-seconds: 60
    key-prefix: rate_limit

logging:
  level:
    root: INFO
    com.example.chatbot.global.config.HttpLoggingFilter: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
